### ISSUE TITLE
Cannot find module 'chartist'

### ISSUE THREAD

**Issue by mogalethali** [creativetimofficial/lbdp-test-login#1]
lbdp-test-login-master/src/app/home/dashboard/dashboard.component.ts (2,27): Cannot find module 'chartist'.)

**Comment by chelaruc** [comment]
@mogalethali thank you for using our products. Can you give us the `npm-debug.log` to see what errors you get?

Keep in touch,
Ciprian

**Comment by mogalethali** [comment]
Good  day,

This solved my issues

" npm install @types/chartist --save-dev "

And the app has what i was looking for. Thanks for your help, i really
appreciate it
